Add NIP-33 Parameterized replaceable events
nostr-protocol/nips pull request #54
Opened 2022-10-16 17:27 UTC by Semisol

NIP-33 allows for parameterized replaceable events which allow replacement by the `d` tag and the kind instead of just the kind.

2022-10-19 15:52 UTC, Cameri approved these changes
LGTM, but please include contributors from the previous PR 🙏

2022-10-20 15:42 UTC, Cameri commented on 33.md
> +`draft` `optional` `author:Semisol`
`Cameri` and `fiatjaf`

2022-10-29 14:58 UTC, Giszmo commented
@Semisol please merge my changes to your PR branch.

* Merge master
* Add nip to Readme.md
* Remove "Client behaviour" as it's redundant
* Define how an empty d-tag would look like: `"tags":["d"]`

2022-11-09 23:02 UTC, Cameri commented
an empty d-tag is all these cases in `nostr-ts-relay`:
`tags:[]`
`tags:[["d"]]`
`tags:[["d", ""]]`

I'm also ensuring uniqueness on one or more possible strings after `"d"` not just the first, so
`["d","1234"]` is different from `["d","1234","abc"]`

2022-11-10 00:04 UTC, Cameri commented
I've implemented this NIP in `nostr-ts-relay`

2022-11-10 21:01 UTC, x1ddos commented on 16.md
> +Upon a replaceable event with a newer timestamp than the currently known latest replaceable event with the same kind being received, the old event SHOULD be discarded and replaced with the newer even
link to nip-33 somewhere around here? if someone's implementing nip-16, they'll probably want to know about nip-33, too.

2022-11-18 15:39 UTC, Giszmo commented
> an empty d-tag is all these cases in `nostr-ts-relay`: `tags:[]` `tags:[["d"]]` `tags:[["d", ""]]`
> 
> I'm also ensuring uniqueness on one or more possible strings after `"d"` not just the first, so `["d","1234"]` is different from `["d","1234","abc"]`

Would `["d","1234","abc"]` be equal to `["d","1234abc"]` though? If not this or any similar concatenation of the strings, I don't agree with considering further elements of the tag.

2022-11-20 21:14 UTC, Giszmo commented on 33.md
> +A missing `d` tag should be interpreted as an empty tag value and only the first tag's value should be accounted for.
I agree with Semisol. Having to consider more values makes the code more complex for no obvious benefit.

It's the same argument why we ignore secondary d-tags, right? Else you could consider all d-tags and all their strings and of course their order for deduplication.

2022-11-22 22:03 UTC, Giszmo requested changes
Please look into https://github.com/Semisol/nips/pull/1

For example  the main Readme has to also list this nip.

2023-01-04 13:07 UTC, fiatjaf commented
Can we merge this?

2023-01-04 13:17 UTC, Cameri commented
> Can we merge this?

Probably. It's already implemented on Nostream

2023-01-04 13:20 UTC, merged

2023-01-04 13:20 UTC, fiatjaf commented
I don't know why my name is on this NIP since all I did was to trash it since day one.

2023-01-04 13:21 UTC, grunch commented
> 

I'm just reading this, probably this is what I need, I'll test it with nostream right now, thanks for this NIP

2023-01-04 13:21 UTC, fiatjaf commented
@Giszmo it looks like @Semisol has ignored your proposed changes, but I think we should still merge them, if you have the patience to open a new PR to this repo. Or we can do that later.

2023-01-04 13:24 UTC, Cameri commented
> @fiatjaf  I'm just reading this, probably this is what I need, I'll test it with nostream right now, thanks for this NIP

There's one change I need to make on Nostream. But if you use it as per this NIP you won't notice the difference.

2023-01-04 14:34 UTC, grunch commented
@Cameri I'm not sure if I'm misunderstanding this nip, I published two events to a nostream relay:

```json
  {
    "id": "1d1b3b1f3d7f3e3d1a59564f5dcdea5ed1c230086941419f0491217e37981956",
    "kind": 10000,
    "pubkey": "dbe0b1be7aafd3cfba92d7463edbd4e33b2969f61bd554d37ac56f032e13355a",
    "created_at": 1672842546,
    "content": "{\"id\":50,\"kind\":\"Sell\",\"status\":\"Pending\",\"amount\":222,\"fiat_code\":\"VES\",\"fiat_amount\":4010,\"payment_method\":\"lemon cash\",\"prime\":1,\"created_at\":1672842546}",
    "tags": [
      [
        "d",
        "49"
      ]
    ],
    "sig": "c0e5fd992125824bcc01a0dbef3f271e5c5a4f57f7de403068d1313ffb0afb124b777f64165a8f995185ee68210d6e29f2b607cb275093cda87d503596cbf78c"
  }
```
and

```json
  {
    "id": "1d1b3b1f3d7f3e3d1a59564f5dcdea5ed1c230086941419f0491217e37981956",
    "kind": 10000,
    "pubkey": "dbe0b1be7aafd3cfba92d7463edbd4e33b2969f61bd554d37ac56f032e13355a",
    "created_at": 1672842546,
    "content": "{\"id\":50,\"kind\":\"Sell\",\"status\":\"Pending\",\"amount\":222,\"fiat_code\":\"VES\",\"fiat_amount\":4010,\"payment_method\":\"lemon cash\",\"prime\":1,\"created_at\":1672842546}",
    "tags": [
      [
        "d",
        "50"
      ]
    ],
    "sig": "c0e5fd992125824bcc01a0dbef3f271e5c5a4f57f7de403068d1313ffb0afb124b777f64165a8f995185ee68210d6e29f2b607cb275093cda87d503596cbf78c"
  }
```
When I try to get them with noscat with kind `10000` I just get the last one, is that ok?

2023-01-04 15:22 UTC, grunch commented
Forget my last comment, I didn't change the kind, with kind `30000` it works as it should, great job 🥳