add NIP-19: bech32-encoding of stuff.
nostr-protocol/nips pull request #57
Opened 2022-10-31 13:44 UTC by fiatjaf

With an extra section for TLV-encoded arbitrary metadata. Let me know what you think.

I think this will be very much necessary, for example, for Minds-like integrations through which some profiles and events will generally be only accessible from one master relay from each platform (e.g. the Minds relay). @ottman @harding what do you think?

And also when the network grows and we start to see more segregation of contents between relays, this makes it easier for people to share their profiles, without having to say: "my pubkey is X, and please make sure to add relay Z to your client".

https://github.com/nostr-protocol/nips/blob/ce4869b9404b9c588ef92353999cbe787cb679c3/19.md

Is this correct @jb55? What else are you bech32-encoding? Event ids?

2022-10-31 14:25 UTC, harding commented
What is bech32-2?

2022-10-31 15:03 UTC, jb55 commented
balas makes a good point that the TLV might seem confusing on npubs since it changes your identifying key which people might partially memorize (i do this already for my npub). Also this screws up npub rendering in damus and I would have to figure out another way to display it, but both of these issues aren't too bad for me to deal with.

2022-10-31 16:58 UTC, jb55 commented
On Mon, Oct 31, 2022 at 08:07:52AM -0700, William Casarin wrote:
>damus uses npub,nsec,note
>
>That way there is a uniform way of mentioning entities when you @ then in posts. Damus also will detect when you accidentally do @nsec and convert it to an npub mention.

I'll probably add nchan as well to reference channel ids

2022-10-31 17:31 UTC, fiatjaf commented
Well, the first characters of an npub with or without TLVs will always be the same, and you can shrink it when displaying, it is too big to be comfortable anyway even without TLVs.

2022-11-09 15:57 UTC, jb55 commented
>Parsers must expect to decode extra metadata that may exist after the initial 32 bytes. Any metadata must be added as a `TLV` (type-length-value) item, with `T` and `L` being 2 bytes (`uint16` big-endian) each, and `V` being of the size indicated by `L`.

You mentioned you prefer 1 byte instead of 2? I'm happy with either.

2022-11-09 16:24 UTC, fiatjaf commented
Yes, I wrote this just copying from the BOLT spec, but I can change to 1 byte.

2022-11-09 16:25 UTC, fiatjaf commented
Are we going forward with this? 

I was right now going to say I was liking this design again more than the `nshare1` idea because I also think it would be interesting to have relays inside `note1` strings, so you could be sure that note would show up on other clients when you shared it.

Althougn that is not a direct argument against `nshare1` and might as well be an argument for `nshare1`.

2022-12-15 17:46 UTC, fiatjaf commented
I've revamped this PR. Please agree now.

2022-12-15 19:19 UTC, eskema reviewed
minor stuff

2022-12-15 19:19 UTC, eskema commented on 19.md
> +This NIP species all bech32-encoded entities.
This NIP specifies all bech32-encoded entities.

2022-12-15 19:19 UTC, eskema commented on 19.md
> +These are the possible bech32 prefixes:
These are the possible bech32 prefixes with `TLV`:

I think it makes sense to speficy that these are the ones with a TLV, so it's a different line than from above..

2022-12-15 19:19 UTC, eskema commented on 19.md
> +  - A relay in which the entity (profile or event) is more likely to be found. This may be be included multiple times.
- A relay in which the entity (profile or event) is more likely to be found. This may be included multiple times.

2022-12-15 22:13 UTC, Giszmo requested changes
The NIP should clarify that bech32 is only a representation format. Serialized events may not use these.

I would also suggest clients to only talk about for example "public key":

```
Enter your public key: 
```

but accept legacy hex, too.

The nip could suggest client apps to warn users when a hex key could also be a private key but that's tricky.

2022-12-16 04:40 UTC, monlovesmango commented
I agree. but my opinion matters very little bc I don't know much about this encoding stuff. will be cool to be able to share relay with a pubkey.

2022-12-16 04:42 UTC, monlovesmango approved these changes

2022-12-16 14:56 UTC, merged

2022-12-30 20:51 UTC, ok300 commented
Just curious, why bech32 and not bech32m?

AFAIK the former has a checksum vulnerability when it ends with a p, which is fixed in the later.

2022-12-31 02:22 UTC, fiatjaf commented
Because that's how it was implemented first and it wasn't worth the trouble changing. I believe the vulnerability isn't very meaningful in the context of Nostr.