nip16: clarify about the signers of replaceable events
nostr-protocol/nips pull request #63
Opened 2022-11-10 22:19 UTC by x1ddos

A newer replaceable event must be signed by the same key or a delegation if NIP-26 is implemented.

2022-11-10 23:26 UTC, jb55 commented
LGTM

2022-11-11 01:15 UTC, Cameri requested changes
I don't think this belongs here. Please ddd this clarification to NIP-26 instead of NIP-16 otherwise people seeking to implement NIP-16 need to care about NIP-26 even if they don't implement it.

2022-11-11 01:29 UTC, x1ddos commented
changed the part about nip-26 to:

> or a delegated keypair if NIP-26 is implemented

@Cameri if a relay doesn't implement nip-26, it shouldn't care about it at all.

2022-11-11 01:36 UTC, Cameri commented
> changed the part about nip-26 to:
> 
> > or a delegated keypair if NIP-26 is implemented
> 
> @Cameri if a relay doesn't implement nip-26, it shouldn't care about it at all.

exactly the reason why we should add this to NIP-26 instead

2022-11-11 01:41 UTC, x1ddos commented
ok, on a second thought maybe it is simpler. i removed nip-26 from here.

2022-11-11 01:42 UTC, Cameri approved these changes

2022-11-11 10:56 UTC, merged