`CLOSED` messages for relays that want to reject REQs and NIP-42 `AUTH` integration
nostr-protocol/nips pull request #902
Opened 2023-11-27 18:46 UTC by fiatjaf

I will quote my own message from https://github.com/nostr-protocol/nips/pull/841#issuecomment-1828345933 to explain this:

> Basically we have two distinct problems:
> 
> 1. knowing why a relay is asking for `AUTH`
> 2. knowing why a subscription has failed
> 
> adding a third element to `AUTH` only solves them in the occasion that the two happen together.
> 
> creating a new message solves 2 and making `AUTH` be subservient to that (and also to `OK`) solves 1.

2023-11-27 19:01 UTC, monlovesmango commented on 42.md
> +- `"restricted: "` - for when a client has already performed `AUTH` but the key used to perform it is still not allowed by the relay.
```suggestion
- `"restricted: "` - for when a client has already performed `AUTH` but the key used to perform it is still not allowed by the relay or is exceeding it's authorization.
```

2023-11-27 19:06 UTC, monlovesmango commented
some minor changes, but I approve.

personally think we should just use "CLOSE" rather than "CLOSED" to mirror the client side "CLOSE" (in the same way that "EVENT" is the same on client and relay sides and mean the same thing). seems way more consistent to me.

2023-11-27 19:19 UTC, monlovesmango approved these changes

2023-11-27 19:52 UTC, arthurfranca commented
ACK!! The flow is very clear now with examples and all.

Personally I would just tell relays to always send AUTH right after connection is established. It leaves less room for errors (like sending CLOSED/OK before AUTH).

2023-11-27 20:06 UTC, staab approved these changes

2023-11-27 21:06 UTC, monlovesmango commented
should this also apply to nip 45?

2023-11-28 18:58 UTC, mikedilger commented
+1

2023-11-28 22:32 UTC, proudmuslim-dev requested changes

2023-11-28 22:32 UTC, proudmuslim-dev commented on 42.md
> +At any moment the relay may send an `AUTH` message to the client containing a challenge. The challenge is valid for the duration of the connection or until another challenge is sent by the relay. The
```suggestion
At any moment the relay may send an `AUTH` message to the client containing a challenge. The challenge is valid for the duration of the connection or until another challenge is sent by the relay. The client MAY decide to send its `AUTH` event at any point and the authenticated session is then valid for the remainder of the connection.
```

2023-11-29 16:29 UTC, fiatjaf commented
Implemented in https://nostr.wine

2023-11-29 16:32 UTC, nostr-wine commented
Ha - you beat me to it. We implemented CLOSED with the new flow for DM REQs on all nostr.wine regional relays and will work on the rest of our relays today.

2023-12-06 15:01 UTC, merged