NIP-32: Clarify Language in summary
nostr-protocol/nips pull request #935
Opened 2023-12-19 12:36 UTC by dskvr

The language in the introductory paragrpah is misleading. 

```
A label is a `kind 1985` event that is used to label other entities.
``` 

Is not an accurate statement, particularly as the opening sentence. The definition is out of order when it comes to communicating the purpose of the NIP. 

If summarizing NIP-32 in it's entirety: 

```
A label is two  new indexable tags used label events. It additionally adds an event kind used for labeling other events. 
```

As written, it requires an implementer to read the entire NIP before it is communicated that `l` and `L` tags may be applied to any event.

2023-12-19 16:04 UTC, staab approved these changes

2023-12-21 19:21 UTC, vitorpamplona commented
How about

`This NIP defines two new indexable tags to label events and a new event kind (`kind:1985`) to attach those labels to existing events. This supports several use cases, including distributed moderation, collection management, license assignment, and content classification.`

2023-12-27 12:25 UTC, dskvr commented
Updated, will squash later.

2023-12-28 15:09 UTC, staab requested changes

2023-12-28 15:09 UTC, staab commented on 32.md
> +This NIP defines two new indexable tags to label events and a new event kind (kind:1985) to attach those labels to existing events. This supports several use cases, including distributed moderation,
```suggestion
This NIP defines two new indexable tags to label events and a new event kind (`kind:1985`) to attach those labels to existing events. This supports several use cases, including distributed moderation, collection management, license assignment, and content classification.
```

2024-07-29 16:17 UTC, staab approved these changes

2024-07-29 16:18 UTC, merged